services:
  - type: web
    name: rdb-database
    env: docker
    plan: free
    docker:
      dockerfilePath: Dockerfile
    envVars:
      - key: DOTNET_RUNNING_IN_CONTAINER
        value: "true"
    autoDeploy: false
