services:
  - type: web
    name: chunked-file-api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    branch: main
    autoDeploy: true
    buildCommand: ""
    startCommand: ""
